### ISSUE TITLE
custom background color: window "Pick a color"

### ISSUE THREAD

**Issue by antrrax** [linuxmint/mint19.2-beta#4] opened 2019-07-17 00:43 UTC
**Describe the bug**
When choosing a custom color for the desktop. It should display in the "Pick a color" window the selected color. However it always displays the same color: # BF4040.

**To Reproduce**
<a href="https://ibb.co/gZgjVjd"><img src="https://i.ibb.co/gZgjVjd/ksnip-20190716-212511.png" alt="ksnip-20190716-212511" border="0"></a>

**Expected behavior**
The right one would be the selected color in the "Background color" option to be displayed in the "Pick a color" window, instead of always displaying color # BF4040 when displaying the "Pick a color" window.

**Frequency**
Does the issue happen:
- [x ] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x ] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x ] Post-install
- [ ] Live session

note:The background color selection of the desktop occurs as expected.
The problem is just this detail of the "Pick a color" menu does not remember which color was selected when the window was opened

**Comment by RavetcoFX** [comment] 2019-07-17 01:00
This is not a bug, it does remember the color you picked next to the color picker box, BF4040 is just the default color in the picker. 
![Screenshot from 2019-07-16 18-59-05](https://user-images.githubusercontent.com/1816681/61339646-fb85f180-a7fb-11e9-8a6b-7cb73bb301be.png)

**Comment by antrrax** [comment] 2019-07-17 01:42
How it should work: Example - I preselect a color Blue # 0000FF, then when I open ### **again** the window "Pick a Color" The Blue color would be displayed in the color map and from there I select another similar blue tone. The problem is that the "Pick a Color" window always starts with color # BF4040

The "Pick a Color" window should start with the color selected earlier.

**Comment by RavetcoFX** [comment] 2019-07-17 01:46
This is out of scope as this is with a GTK color picker dialog, Mint has no control over. Please submit  bug with https://gitlab.gnome.org/GNOME/gtk

**Closed** 2019-07-17 09:48 UTC
