### ISSUE TITLE
ubiquity: Selecting a keyboard layout doesn't apply it until the Continue button is pressed

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.2-beta#21] opened 2019-07-17 20:38 UTC
In MATE version, I choose keyboard "Français - Français (variante)". I test it by pressing the keys ² and ³ (shift ²). But I obtain `~ or sometimes œŒ instead of ²³. I must click on the "Continue" button and then on the "Précédent" button to obtain ²³ when I press ²³.
![Installation_2](https://user-images.githubusercontent.com/3955499/61409886-7970f800-a8e3-11e9-8538-8a268cec47d6.png)

**Comment by clefebvre** [comment] 2019-07-19 08:32
![image](https://user-images.githubusercontent.com/1138515/61521408-71fb3d00-aa10-11e9-8cdf-433cf4be29bc.png)

![image](https://user-images.githubusercontent.com/1138515/61521460-86d7d080-aa10-11e9-981b-0534ed61f059.png)

![image](https://user-images.githubusercontent.com/1138515/61521473-8dfede80-aa10-11e9-95f9-f298bd3c8850.png)

**Comment by clefebvre** [comment] 2019-07-19 08:43
OK, the layouts look OK. The issue isn't specific to French, when you select a layout and a variant, it doesn't actually modify it until you click continue. Assuming it should, the entry to test your layout is confusing because it lets you believe that should be the case.

**Comment by clefebvre** [comment] 2019-07-20 09:31
I get the feeling this is related to the fr-latin9 situation. If I choose English, changing variants works fine...

**Comment by clefebvre** [comment] 2019-07-20 19:53
This issue doesn't happen in Ubuntu... and updating console-setup doesn't help... hmm..

**Comment by clefebvre** [comment] 2019-07-25 12:02
It seems to be related to missing translations in ubiquity's kbdnames.gz

**Comment by clefebvre** [comment] 2019-07-25 14:28
Fixed in ubiquity 18.04.1+linuxmint15.

**Closed as completed by clefebvre** 2019-07-25 14:28 UTC
