### ISSUE TITLE
marco: Screenshots of installation windows haven't a transparent background

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint19.2-beta#16] opened 2019-07-17 19:07 UTC
In MATE version, the "Take Screenshot" or "Kazam" applications don't take screenshots of installation Windows with transparent background.
Example : see joined file. It's the screenshot of an installation window. The up right and left corners are round. The background around these corners should be transparent but it's black (because black is the color of the Mint MATE desktop).
Is it a bug or is it because I'm installing Linux Mint MATE in VirtualBox ?
![Installation_5](https://user-images.githubusercontent.com/3955499/61404040-d6b27c80-a8d6-11e9-9c38-7ba14cf855eb.png)

**Comment by corbin-auriti** [comment] 2019-07-18 00:46
How are you taking a screenshot? When I choose grab the current window I get a small border of what was behind it. If you're using Kazam, then it's not related to Mate or Mint

**Comment by InfoLibre** [comment] 2019-07-18 18:30
I grab the current window with "Take Screenshot", available in Linux Mint MATE live ISO.
After, I tested with the package Kazam that I installed in the live system, the problem is the same with the 2 softwares.

**Comment by InfoLibre** [comment] 2019-07-18 18:32
With "Take Screenshot", I had this results too :
![Langue_5](https://user-images.githubusercontent.com/3955499/61482508-16429c80-a99b-11e9-9f5b-a139ba064c94.png)
![Langue_3](https://user-images.githubusercontent.com/3955499/61482551-2bb7c680-a99b-11e9-87f4-e7c876ac3915.png)

It's like the shadow of the windows is captured too.

**Comment by corbin-auriti** [comment] 2019-07-18 18:52
~~I believe this works as intended. If you need it transparent you may have to use a third party tool or image editing software~~

**Comment by InfoLibre** [comment] 2019-07-18 18:54
It's a joke ?

**Comment by corbin-auriti** [comment] 2019-07-18 19:03
I'm sorry, is all your referring to the black pixels? I thought you meant it should have an alpha value. From the looks of your other screenshots I don't see the black pixel, so it seems might have been the virtualbox or compositor you're using.

**Comment by InfoLibre** [comment] 2019-07-18 19:11
A window screenshot on my real computer, with "Take Screenshot", Linux Mint MATE 19.2 :
![Capture du 2019-07-18 21-08-01](https://user-images.githubusercontent.com/3955499/61485069-90295480-a9a0-11e9-801f-09145ea6c657.png)

No colored pixel in the corner, no shadow and a transparent background. Impossible to do that with Linux Mint MATE 19.3 in VirtualBox.

**Comment by clefebvre** [comment] 2019-07-19 08:22
@monsta you mentioned an issue with invisible borders in Marco 1.22.2? Could this be related?

**Comment by monsta** [comment] 2019-07-19 10:34
Yes, it's due to invisible borders :slightly_frowning_face:

**Comment by monsta** [comment] 2019-07-19 10:35
See also https://github.com/mate-desktop/mate-utils/issues/236

**Comment by clefebvre** [comment] 2019-07-20 09:08
Ok, it's not a release blocker on our side so I'll close this. We'll push the fix as an update if we manage to fix it upstream in MATE 1.22.

**Closed as completed by clefebvre** 2019-07-20 09:08 UTC
